apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacker-leo-oh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacker-leo-oh
  template:
    metadata:
      labels:
        app: hacker-leo-oh
    spec:
      containers:
      - image: okteto.dev/hacker-leo-oh:latest
        name: leo-oh
        envFrom:
        - configMapRef:
            name: leo-oh-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: hacker-leo-oh
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "hacker-leo-oh"
    port: 8080
  selector:
    app: hacker-leo-oh
